### ISSUE TITLE
Request package no longer maintained

### ISSUE THREAD

**Issue by yongzhihuang** [docluv/ping_bing#1]
Hi!
https://www.npmjs.com/package/request the request lib is being deprecated.  Is it possible to update this lib to use native request lib or something like node-fetch https://www.npmjs.com/package/node-fetch? instead?

**Comment by docluv** [comment]
Yeah I just saw the request library was retired yesterday and I'm going to see what I can do in the next few days

On Feb 26, 2020 5:37 PM, Yongzhi Huang <notifications@github.com> wrote:

Hi!
https://www.npmjs.com/package/request the request lib is being deprecated. Is it possible to update this lib to use native request lib or something like node-fetch https://www.npmjs.com/package/node-fetch? instead?

**Comment by docluv** [comment]
I replaced request with the node native https functions a while back. So there should be no dependency now.
