### ISSUE TITLE
GetUrlSubmissionQuota

### ISSUE THREAD

**Issue by maxNodeJs** [docluv/ping_bing#2]
Would be nice if you update the plugin to check Submission Quota before submitting to Bing. So it check how many urls can be submitted. I guess it is not essential, however, it would be good option so developers can put the none submitted urls into a cue.

Here is info from bing.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.bing.webmaster.api.interfaces.iwebmasterapi.geturlsubmissionquota?view=bing-webmaster-dotnet

**Comment by docluv** [comment]
Sounds like a nice request. I will check into that and add this as soon as I can.
Not even sure if that was available 2 years ago with the API was first released. So thanks for bringing this up.

**Comment by docluv** [comment]
pushed an update
